import { Book } from '../class/book';
export const Books: Book[] = [
	{ id: 0, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 1, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 2, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 3, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 4, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 5, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 6, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 7, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 8, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 9, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 10, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 11, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 12, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 13, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 14, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 15, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 16, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 17, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 18, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 19, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
	{ id: 20, title: 'fasdfads', author: 'fasdfasf', category: 'asdffaf', price: 445, description: 'fasfdasff' },
];